chanzuckerberg/single-cell-explorer

- client/src/actions/annotation.ts
- client/src/actions/embedding.ts
- client/src/actions/index.ts
- client/src/reducers/index.ts
- client/src/util/actionHelpers.ts
> feedback: thuang-2366-feedback

- backend/czi_hosted/data_common/dataset_metadata.py
- backend/test/test_czi_hosted/unit/common/test_api.py
- @ebezzi 
---
- modify dataset metadata retrieval code to properly handle response body
> fix: dataset metadata response parsing

- backend/czi_hosted/requirements.txt
@MDunitz 
@ebezzi 
---
- modify: upgraded tiledb to `>=0.9`
> fix: upgraded tiledb (#2251)

- client/__tests__/util/centroid.test.ts
- client/__tests__/util/stateManager/colorHelpers.test.ts
- client/src/actions/index.ts
- client/src/annoMatrix/annoMatrix.ts
- client/src/annoMatrix/viewCreators.ts
- client/src/components/autosave/filenameDialog.tsx
- client/src/components/categorical/index.tsx
- client/src/components/infoDrawer/infoDrawer.tsx
- client/src/reducers/categoricalSelection.ts
- client/src/reducers/colors.ts
- client/src/reducers/genesets.ts
- client/src/util/dataframe/dataframe.ts
- client/src/util/stateManager/annotationsHelpers.ts
- client/src/util/stateManager/colorHelpers.ts
- client/src/util/stateManager/controlsHelpers.ts
- client/src/util/stateManager/index.ts
- client/src/util/stateManager/matrix.ts
- client/src/util/stateManager/schemaHelpers.ts
- client/src/util/stateManager/viewStackHelpers.ts
- client/src/util/typedCrossfilter/crossfilter.ts
This PR covers `client/src/util/stateManager` with commits in diff! PTAL thank you 🙏
> Thuang 10 type state manager

- client/__tests__/e2e/screenshot_env.js
this is a follow up for https://github.com/chanzuckerberg/single-cell-explorer/pull/75
Thank you!
> chore: disable e2e debugging code

- client/src/common/types/entities.ts
- client/src/components/infoDrawer/infoDrawer.tsx
- client/src/components/infoDrawer/infoFormat.tsx
- client/src/components/util/version.ts
@seve 
@ebezzi 
---
Added types! 
Thanks all 🙏
> chore: Add types for recognized version commit

- server/app/app.py
Proof that it's working locally 🙆‍♂️ Thank you!
---
- add
- remove
- modify
> fix: 84 Do not cache index.html

- client/__tests__/e2e/puppeteer.setup.ts
- client/configuration/eslint/eslint.js
- client/package-lock.json
- client/package.json
- client/src/actions/index.ts
- client/src/components/brushableHistogram/header.tsx
- client/src/components/brushableHistogram/histogram.tsx
- client/src/components/categorical/category/index.tsx
- client/src/components/datasetSelector/datasetSelector.tsx
- client/src/components/geneExpression/quickGene.tsx
- client/src/components/scatterplot/scatterplot.tsx
> Thuang feedback seamless

- dev_docs/cxg.md
for optional fields, specify which version it applies to
> minor cxg spec update

- client/src/common/types/entities.ts
- client/src/components/categorical/index.tsx
- client/src/components/continuous/continuous.tsx
- client/src/components/infoDrawer/infoFormat.tsx
- client/src/globals.ts
- client/src/util/collapse/index.tsx
@tihuan
---
Added accordion for standard and author categories as well as continuous.
> Add standard categories, author categories and continuous accordions to left sidebar. (#118)

- client/src/components/infoDrawer/infoDrawer.tsx
- client/src/components/infoDrawer/infoFormat.tsx
- client/src/components/menubar/index.tsx
@tihuan, @seve 
---
* Removed data portal props prop from drawer as organism is now accessed via obs.
* Fixed link sort order.
> Removed data portal props from drawer. (#89)

- client/src/components/geneExpression/quickGene.tsx
> fix: Revert quickGene partially

- client/src/components/brushableHistogram/index.tsx
- client/src/components/brushableHistogram/loading.tsx
- client/src/components/categorical/category/index.tsx
- client/src/components/graph/graph.tsx
- client/src/components/leftSidebar/leftSidebarSkeleton.tsx
@tihuan 
---
- Added super categories to skeleton.
- Updated categorical and continuous loading indicator to match skeleton-style gray bar.
- Removed swirl load indicator for graph.
> Updated load indicator to match skeleton. (#139)

- client/src/components/categorical/index.tsx
@tihuan, @seve 
---
- Updated calculations of standard and author categories for display in the LSB.
> Updated author supercategory partitioning. (#136)

- server/app/api/__init__.py
- server/app/api/v3.py
**Functional:** @atolopko-czi 
**Readability:** @ebezzi
> fix: add max_age to immutable caches

- LICENSE.txt
**Functional:** @atolopko-czi 
**Readability:** N/A
---
- Updating the year on our license to include 2022.
> Update license to 2022.

- client/src/common/types/entities.ts
- client/src/components/infoDrawer/infoFormat.tsx
@tihuan 
---
- Added summary citation to dataset drawer ([mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1722%3A55955)).
> Added summary citation to dataset drawer. #211

- client/__tests__/util/diffexpdu.test.ts
- client/src/util/diffexpdu/diffexpdu.ts
- client/src/util/diffexpdu/index.ts
- client/src/util/diffexpdu/pdubuffer.ts
- client/src/util/diffexpdu/postingslist.ts
- client/src/util/diffexpdu/utils.ts
- dev_docs/diffexpdu.md
- scripts/diffexpdu/README.md
- scripts/diffexpdu/codecTest.py
- scripts/diffexpdu/codecTest.ts
- scripts/diffexpdu/genTestSpec.py
- server/common/diffexpdu/__init__.py
- server/common/diffexpdu/diffexpdu.py
- server/common/diffexpdu/postingslist.py
- server/common/diffexpdu/utils.py
- server/requirements.txt
- server/tests/unit/common/test_diffexpdu.py
Initial Python and TypeScript modules supporting the encoding/decoding of the differential expression PDU.
* TS module in client/src/util/diffexpdu
* Py package in server/common/diffexpdu
* format spec in dev_docs/diffexpdu.md
* scripts to do Typescript/Python compatibility in scripts/diffexpdu 
Also includes basic unit tests.
> diffex PDU support

- hosted/requirements.txt
- server/dataset/cxg_dataset.py
- server/requirements.txt
- server/tests/unit/dataset/test_cxg_dataset.py
* bump tiledb to 0.13.1, add work-around for dense read bug
* use old style python
> chore: dev->staging

- client/src/components/infoDrawer/infoFormat.tsx
@tihuan 
---
- Removed filter flag switches.
> Removed filter flag. #1718

- .happy/terraform/modules/ecs-stack/main.tf
- hosted/Dockerfile
- hosted/requirements.txt
@atolopko-czi 
---
- add
- remove
- modify
> chore: use gunicorn for ecs

- .github/workflows/deploy-happy-stack.yml
> chore: bump happy to 0.19.1

- hosted/create_env_config.py
> chore: stage -> staging in the config generation file

- client/src/components/brushableHistogram/index.tsx
- client/src/components/categorical/category/index.tsx
- client/src/components/categorical/value/index.tsx
- client/src/components/geneExpression/gene.tsx
> fix: same category and gene name coloring issues

- hosted/Dockerfile
> fix(docker): explicitly install node

- hosted/config.yaml
@atolopko-czi 
---
- add
- remove
- modify
> chore: add missing config.yaml file

- hosted/Dockerfile
@ebezzi 
@Bento007 
---
- modify Dockerfile to combine RUN statements into one layer for slight performance improvement
> fix: combine run statements into one layer

- client/src/components/geneExpression/gene.tsx
- client/src/components/geneExpression/index.tsx
- client/src/components/geneExpression/quickGene.tsx
- client/src/globals.ts
… smoke tests
---
- added checks for "feature_id" to pass smoke tests
- returned rightsidebarwidth to original
- Created this PR to fix smoke test issues in gene info PR
- Merged #320 into this PR, so there are a few minor design changes too
> chore: fix gene info to pass smoke tests

- .happy/terraform/modules/ecs-stack/main.tf
- hosted/Dockerfile
- hosted/nginx.conf
- hosted/start.sh
@ebezzi 
@atolopko-czi 
---
- added an nginx reverse proxy to route requests to the gunicorn server and compress outgoing responses
> Added gzip compression to outgoing responses via an nginx reverse proxy

- .github/workflows/push-rdev.yml
- .happy/requirements.txt
- .happy/terraform/modules/ecs-stack/main.tf
- hosted/Dockerfile
- hosted/nginx.conf
- hosted/start.sh
> chore: deploy prod <- staging

- server/common/config/app_config.py
- server/eb/app.py
@MDunitz 
---
- add
- remove
- modify
> chore: restore logs

- .happy/terraform/envs/dev/providers.tf
- .happy/terraform/envs/prod/providers.tf
- .happy/terraform/envs/staging/providers.tf
@alexlokshin-czi 
---
- add
- remove
- modify
> chore: upgrade aws provider

- .happy/terraform/envs/rdev/main.tf
> chore: increase rdev memory

- client/__tests__/e2e/e2e.test.ts
- client/__tests__/e2e/puppeteerUtils.ts
- client/src/components/geneExpression/geneSet.tsx
> test(smoketest): Update diff exp test

- client/index.html
- client/src/components/NavBar/style.ts
- client/src/index.css
---
Update Explorer to use the same font size files as Data Portal, also add global style `-webkit-font-smoothing: antialiased;` per Data Portal 👌
> fix(navbar): font display

- client/src/actions/index.ts
- client/src/components/geneExpression/gene.tsx
- client/src/components/geneExpression/geneInfo/geneInfo.tsx
- client/src/components/leftSidebar/index.tsx
- client/src/reducers/controls.ts
@seve 
---
- incorporate new "show_warning_banner" response param into explorer frontend code
> chore: gene info warning banner response

- server/requirements.txt
> chore: upgrade tiledb to 0.16.5

- hosted/requirements.txt
> chore: upgrade tiledb to 0.16.5 part 2

- hosted/Dockerfile
> chore(node): Upgrade to 16 in Dockerfile

- server/eb/.ebextensions/enable_mod_deflate.config
- server/eb/.ebextensions/wsgi_app_group_global.config
- server/eb/Makefile
- server/eb/app.py
- server/eb/check_config.py
- server/eb/check_requirements.py
- server/eb/config_deploy.yaml
Reverts chanzuckerberg/single-cell-explorer#503
> Revert "refactor: Remove elastic bean stock path"

- server/common/compute/estimate_distribution.py
- server/common/config/app_config.py
- server/common/config/base_config.py
- server/common/config/external_config.py
- server/common/config/server_config.py
- server/common/constants.py
- server/common/diffexpdu/postingslist.py
- server/dataset/cxg_dataset.py
- server/dataset/cxg_util.py
- server/dataset/dataset.py
- server/tests/unit/common/config/test_external_config.py
- server/tests/unit/common/test_diffexpdu.py
**Functional:** @danieljhegeman 
**Readability:** @ashin-czi 
---
- add
- remove
- modify
> refactor: Change type checking to isinstance check.

- client/src/actions/index.ts
- client/src/reducers/genesets.ts
- server/app/api/v3.py
- server/common/rest.py
- server/tests/e2e/test_api_cache.py
- server/tests/unit/common/apis/test_api_v3.py
- #214 
**Functional:** @atarashansky 
**Readability:** @danieljhegeman 
---
- add
- remove
- modify
> remove Get genesets call

- client/__tests__/e2e/data.ts
- client/src/actions/index.ts
- client/src/components/app.tsx
- client/src/components/framework/layout.tsx
- client/src/components/framework/layoutSkeleton.tsx
- client/src/reducers/datasetMetadata.ts
https://github.com/chanzuckerberg/single-cell-explorer/issues/501
> fix: Assume navbar present by default and only remove padding if dataset metadata errors

- hosted/start.sh
- server/Makefile
@Bento007 
---
- add
- remove
- modify
> fix: wrong path in start.sh

- server/ecs/Makefile
- server/ecs/app.py
- server/ecs/check_config.py
- server/ecs/check_requirements.py
> fix: add missing ECS folder

- client/src/common/types/entities.ts
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3157
> chore: remove terms deprecated in schema 3.0.0 from standard categories

- client/src/common/types/entities.ts
* chore: remove terms deprecated in schema 3.0.0 from standard categories
> chore: staging deploy

- LICENSE.txt
https://github.com/chanzuckerberg/single-cell/issues/403
> chore: Update license copyright year

- client/__tests__/e2e/cellxgeneActions.ts
- client/__tests__/e2e/e2e.test.ts
- client/src/components/graph/graph.tsx
- client/src/util/camera.ts
* feat: increase zoom limits by a factor of 4
> staging deploy; 4/25/23

- .github/workflows/deploy-happy-stack.yml
- .github/workflows/push-rdev.yml
* fix: upgrade github actions
* retrigger github actions
* add permissions block
> chore: staging 5/9/23

- server/app/app.py
- server/app/logging.py
- server/app/request_id.py
- server/requirements.txt
- server/tests/unit/common/apis/test_api_v3.py
- Add a unique request_id to all messages logged per request.
- Return a unique X-Request-ID that correlated with log messages produce during a request.
- Add JSON log formatter to format all logs into JSON.
- Fixes #581
> feat: Add correlation ids to logs to improve debugging

- server/requirements.txt
Fixes https://github.com/chanzuckerberg/single-cell-data-portal/issues/4893
> chore: upgrade tiledb to 0.21.4

- server/app/app.py
adding `type` as a field in the request and response log messages for the backend server
> add log message type

- dev_docs/developer_guidelines.md
> chore: update dev guidelines for M1/M2 machines

- .happy/catalog-info.yaml
This PR was created with EngPortal using the "Register Existing Happy App in Software Catalog" software template. It creates a component YAML file and registers the component in the Eng-Portal Software Catalog.
> chore: add to software catalog

- .happy/config.json
Update happy config to work with current happy versions
> chore: update happy config task launch type

- .github/workflows/close-stale-prs.yml
- .happy/catalog-info.yaml
- .happy/config.json
* feat: Add a Github Action that automatically closes stale PRs. (#647)
* chore: add to software catalog (#649)
* fix: override default so that issues are not marked as stale (#650)
* chore: update happy config task launch type (#651)
---------
> chore:prod<-staging (#652)

- .happy/config.json
This reverts commit 65e5da036d6c65b2bb89f20e9d1d4886a9822166.
> Revert "chore: update happy config task launch type (#651)"

- .happy/terraform/modules/service/main.tf
- .happy/terraform/modules/service/variables.tf
> fix: fail happy deploy if service does not start successfully

- client/index.html
- client/src/common/types/entities.ts
- client/src/components/categorical/index.tsx
- scripts/explorer-with-portal-rdev.patch
- scripts/patch-explorer-to-find-portal-rdev-stack.sh
* feat: exclude observation join id from standard and author categories (#674)
* exclude observation join id
* don't commit package.json changes
* add stuff back in
* reorder
* fix explorer local dev
* chore: add script to patch explorer to find portal rdev stack (#671)
---------
> chore: deploy prod <- staging (#681)

- server/dataset/dataset_metadata.py
- server/tests/unit/common/apis/test_api_v3.py
> Use canonical collection id for creating collection_url

- client/configuration/webpack/obsoleteHTMLTemplate.html
> fix(explorer): fix image path

- .happy/config.json
This reverts commit 9b4210faa378f1184ec3d863d6e0d1fc506cb146.
> Revert "chore: staging->prod (#722)"

- .github/workflows/deploy-happy-stack.yml
> chore: test artifact upload again

- client/__tests__/e2e/cellxgeneActions.ts
The undo/redo tests seem to be flaky, hopefully tryUntil helps
> test: Add try until

- client/src/globals.ts
Reverts chanzuckerberg/single-cell-explorer#786
> Revert "feat: split new cellguide cxg regex into another constant"

- client/__tests__/e2e/e2e.test.ts
- client/src/globals.ts
- server/app/api/v3.py
- server/app/app.py
Reverts chanzuckerberg/single-cell-explorer#790
> Revert "chore: deploy staging (TEST) 2/24"

- .happy/config.json
- client/src/globals.ts
- server/app/api/v3.py
- server/app/app.py
- server/common/constants.py
- server/common/rest.py
Fixed some bugs that were only visible when testing on a deployed environment. This has been tested with (way too many) pirated deployments to `dev` and all is working.
> feat: fix explorer API for handling subpaths in S3

- client/src/components/graph/graph.tsx
- client/src/components/menubar/index.tsx
- client/src/reducers/controls.ts
- client/src/util/featureFlags/features.ts
#393 
Adds image downloading button
Feature flag: `?dl=true`
Also adds some QOL's for local dev and testing
> feat: enable image capture and download of graph

- hosted/config.yaml
- server/ecs/app.py
Also removes google analytics from CSP
> fix: update CSP to allow for image fetching from backend

- .github/workflows/push_tests.yml
- client/__tests__/e2e/cellxgeneActions.ts
Seems like the tests are just brittle and wrapping them in `tryUntil` should stabilize them 🤞
> test: fix e2e test

- server/dataset/dataset.py
This reverts commit f0d7c626739e77abd2de9689ad92c80e4f44b380.
> Revert "fix: missing uns array returns error instead of None"

- client/configuration/lint-staged/lint-staged.config.js
- client/src/annoMatrix/whereCache.ts
- client/src/components/leftSidebar/infoMenu.tsx
- client/src/components/menubar/clip.tsx
- client/src/util/dataframe/labelIndex.ts
- client/src/util/diffexpdu/utils.ts
There were some latent ts errors in the codebase as a result of lint workflows being written incorrectly. Once the workflows were corrected in #559 some errors arose in main.
> chore: fix latent lint errors

- .github/workflows/push_tests.yml
Currently unit test is timing out after 6 hours
> chore: Add timeout to unit test

- client/__tests__/e2e/cellxgeneActions.ts
- client/__tests__/e2e/e2e.test.ts
- client/__tests__/e2e/playwright.global.setup.ts
- client/playwright.config.ts
- client/src/components/menubar/index.tsx
#871 
Adds some testing to ensure that image downloads are working properly
> test: Create chromatic snapshot testing for image downloads

- client/__tests__/e2e/e2e.test.ts
Context:
1. The test was failing at `const initialOrder = await getAllCategories(categoryName, page);` because it's still showing the loading skeleton, so I added some awaits, tryUntil, and assertions to ensure the arrays have items!
> test: Add await for skeleton before assertions

- client/__tests__/e2e/cell-guide.test.ts
- client/__tests__/e2e/cellxgeneActions.ts
- client/__tests__/e2e/e2e.test.ts
- client/__tests__/e2e/playwright.global.setup.ts
- client/__tests__/util/helpers.ts
- client/configuration/eslint/eslint.js
- client/src/actions/embedding.ts
- client/src/actions/index.ts
- client/src/annoMatrix/annoMatrix.ts
- client/src/components/categorical/value/index.tsx
- client/src/components/datasetSelector/truncatingBreadcrumbs.tsx
- client/src/components/embedding/index.tsx
- client/src/components/geneExpression/index.tsx
- client/src/components/geneExpression/quickGene.tsx
- client/src/components/graph/graph.tsx
- client/src/components/infoDrawer/infoDrawer.tsx
- client/src/components/menubar/index.tsx
- client/src/util/stateManager/viewStackHelpers.ts
This PR adds lint rule `no floating promises` and fixes existing violations!
> fix: no floating promises

- client/__tests__/e2e/cellxgeneActions.ts
- client/__tests__/e2e/data.ts
- client/__tests__/e2e/e2e.test.ts
- client/playwright.config.ts
- client/src/components/embedding/index.tsx
- client/src/components/graph/graph.tsx
- client/src/components/menubar/index.tsx
- client/src/components/util/truncate.tsx
- client/src/util/constants.ts
#934 
1. Remove Chromatic auto snapshot to reduce snapshot noise
2. A few DX improvements
3. Add new and enhance existing tests to capture more test cases
4. Improve a few existing tests to reduce flakiness
5. Disable some tooltips in feature flag `test=true` to reduce flakiness
> test: Add deep zoom e2e tests

- client/src/actions/embedding.ts
- client/src/actions/index.ts
- client/src/components/PanelEmbedding/index.tsx
- client/src/components/PanelEmbedding/util.ts
- client/src/components/embedding/index.tsx
- client/src/components/graph/graph.tsx
- client/src/components/graph/types.ts
- client/src/components/menubar/index.tsx
- client/src/reducers/panelEmbedding.ts
MERGE AFTER #964 
Adds panelEmbedding buttons and logic for:
* Collapsing panel
* expanding panel
* closing panel
* opening panel
* choosing embedding
* put side by side behind spatial ff
> feat(side-by-side): add buttons for collapse, remove, open, also revamp embedding selector

- .infra/rdev/values.yaml
- client/__tests__/e2e/e2e.test.ts
- client/src/components/categorical/category/index.tsx
- client/src/components/categorical/constants.ts
- client/src/components/categorical/index.tsx
- client/src/components/continuous/constants.ts
- client/src/components/continuous/continuous.tsx
1. Add test to prevent regression for bug #1022
> chore: Add test for bug #1022 color by category

- .infra/rdev/values.yaml
- client/package-lock.json
- client/package.json
- client/src/components/diffexNotice/index.tsx
- client/src/components/diffexNotice/style.ts
1. Remove `@mui/material`
2. Fix e2e test failure caused by passing `undefined` instead of a function
> fix: diffexp notif

- .infra/rdev/values.yaml
- client/src/analytics/index.ts
Missed removing console.log in https://github.com/chanzuckerberg/single-cell-explorer/pull/1051
> chore: Turn off logging comments

- .infra/rdev/values.yaml
- client/src/util/layout.ts
#1064 
Added `spatial` to default layout list
> fix: add spatial to default layout list

- .infra/rdev/values.yaml
- client/src/common/selectors.ts
- client/src/components/embedding/index.tsx
- client/src/components/menubar/index.tsx
- client/src/components/menubar/style.ts
- client/src/util/featureFlags/features.ts
⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
DO NOT MERGE THIS PR UNTIL WE GET THE GREEN LIGHT 🚦
⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
> feat: Remove spatial feature flag

- .github/workflows/push_tests.yml
- .infra/rdev/values.yaml
- client/Makefile
Adds Parallelism to GHA. 
Reduces test time from 16min to 9mins. We could add more workers if we like.
> chore: Add parallelism (SCE-14)

- .github/workflows/e2e-tests.yml
- .github/workflows/push_tests.yml
- .github/workflows/scale-test.yml
- .infra/rdev/values.yaml
- dev_docs/developer_scripts.md
- server/common/diffexpdu/postingslist.py
- server/common/fbs/matrix.py
- server/requirements.txt
- server/tests/unit/common/utils/test_type_conversion_utils.py
- server/tests/unit/dataset/test_cxg_dataset.py
- Updated Python version for GHA workflow
- Updated flatbuffers to 2.0.7
- Updated to Scipy 1.14.1 
- Updated unit tests and related code
> chore: Python 3.12 (SCE-16)

- .infra/rdev/values.yaml
- client/src/components/Graph/Graph.tsx
- client/src/components/Graph/openseadragon-scalebar.js
- client/src/global.d.ts
- Updated scale bar position - pinned to bottom right with offset to avoid overlapping with dataset's name
> chore: update scale bar position

- .infra/rdev/values.yaml
- client/src/components/DiffexNotice/style.ts
- client/src/components/MenuBar/components/DiffExpButtons/DiffExpButtons.tsx
- client/src/components/MenuBar/components/DiffExpButtons/components/CellSetButton/CellSetButton.tsx
- client/src/components/MenuBar/components/DiffExpButtons/components/CellSetButton/connect.ts
- client/src/components/MenuBar/components/DiffExpButtons/components/CellSetButton/types.ts
- client/src/components/MenuBar/components/DiffExpButtons/connect.ts
- client/src/components/MenuBar/components/DiffExpButtons/constants.ts
- client/src/components/MenuBar/components/DiffExpButtons/types.ts
- client/src/globals.ts
- client/src/reducers/config.ts
- client/src/reducers/differential.ts
Refactor of `DiffExpButtons` and `CellSetButton`.
> refactor: DiffExpButtons (SCE-34)

- .infra/rdev/values.yaml
- client/__tests__/e2e/e2e.test.ts
- server/common/agent.py
- server/common/tools.py
<details open>
<br />
<table>
<tr>
<th>Name</th>
<td>atar-agent-fix</td>
</tr>
<tr>
<td>clear-firefly</td>
</tr>
<tr>
<td><a href="https://clear-firefly.dev-sc.dev.czi.team" target="_blank">https://clear-firefly.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
> chore: tweak prompts

- .github/workflows/release-please.yaml
- .infra/rdev/values.yaml
https://czi.atlassian.net/browse/CCIE-3911
> chore: remove deprecated tags

- .github/workflows/argus-stack-prod-upsert.yaml
- .github/workflows/argus-stack-rdev-create.yaml
- .github/workflows/argus-stack-rdev-delete.yaml
- .github/workflows/argus-stack-staging-upsert.yaml
- .github/workflows/workflow-argus-docker-build.yaml
- .infra/rdev/values.yaml
<details open>
<br />
<table>
<tr>
</tr>
<tr>
<td>accepted-bunny</td>
</tr>
<tr>
<td><a href="https://accepted-bunny.dev-sc.dev.czi.team" target="_blank">https://accepted-bunny.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
> fix: Update Argus to latest

- client/package-lock.json
- client/package.json
- client/src/common/types/entities.ts
- client/src/components/App/App.tsx
- client/src/index.tsx
<details open>
<br />
<table>
<tr>
</tr>
<tr>
<td>steady-filly</td>
</tr>
<tr>
<td><a href="https://steady-filly.dev-sc.dev.czi.team" target="_blank">https://steady-filly.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
> feat: Add noindex for unpublished datasets

- .infra/prod/values.yaml
- .infra/rdev/values.yaml
- .infra/staging/values.yaml
- hosted/config.yaml
<details open>
<br />
<table>
<tr>
</tr>
<tr>
<td>amazing-sparrow</td>
</tr>
<tr>
<td><a href="https://amazing-sparrow.dev-sc.dev.czi.team" target="_blank">https://amazing-sparrow.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
> feat: add new data root for byod workflow outputs

- server/app/api/v3.py
- server/common/rest.py
- server/dataset/cxg_dataset.py
- Merge geneInfo and coverage endpoints
```
.../api/v0.3/atac/coverage?gene_name=DDX11L2&genome_version=hg38&cell_type=cell
```
> feat: Update coverage endpoint

- .infra/rdev/values.yaml
- client/src/common/components/Embedding/components/ChromatinViewerButton/ChromatinViewerButton.tsx
- client/src/common/queries/cellType.ts
- client/src/components/App/App.tsx
- client/src/components/BottomPanel/BottomPanel.tsx
- client/src/util/featureFlags/features.ts
- vcp-infra/.infra/rdev/values.yaml
<details open>
<br />
<table>
<tr>
<td>vcp-explorer</td>
</tr>
<tr>
<td>guided-pony</td>
</tr>
<tr>
<td><a href="https://guided-pony.dev-vcp.dev.czi.team" target="_blank">https://guided-pony.dev-vcp.dev.czi.team</a></td>
</tr>
</table>
</details>
---
<details open>
<br />
<table>
<tr>
</tr>
<tr>
<td>just-rat</td>
</tr>
<tr>
<td><a href="https://just-rat.dev-sc.dev.czi.team" target="_blank">https://just-rat.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
> feat: Remove ATAC feature flag

- .infra/rdev/values.yaml
- server/dataset/cxg_dataset.py
- vcp-infra/.infra/rdev/values.yaml
<details open>
<br />
<table>
<tr>
<td>vcp-explorer</td>
</tr>
<tr>
<td>summary-sailfish</td>
</tr>
<tr>
<td><a href="https://summary-sailfish.dev-vcp.dev.czi.team" target="_blank">https://summary-sailfish.dev-vcp.dev.czi.team</a></td>
</tr>
</table>
</details>
---
<details open>
<br />
<table>
<tr>
</tr>
<tr>
<td>set-seagull</td>
</tr>
<tr>
<td><a href="https://set-seagull.dev-sc.dev.czi.team" target="_blank">https://set-seagull.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
> fix: e2e after removing ATAC ff
