server/compute/diffexp_cxg.py
server/data_cxg/cxg_adaptor.py
server/requirements.txt

@bkmartinjr, @MDunitz 
@ebezzi 
---
- modify: TileDB-Py version 0.9.5 -> 0.10.0 plus workaround for threading issue
* Bruce provided a [bug repro](https://czi-sci.slack.com/archives/C013K0JB8F8/p1631313728008100) to TileDB which showed that the failure occurs on TileDB-Py versions 0.8.8 and above, including the current version, 0.10.0.
* This temporary workaround was [suggested by Seth](https://czi-sci.slack.com/archives/C013K0JB8F8/p1631314319012700) from TileDB and refined by Bruce to avoid hitting the cached `X` and `X_col_shift` arrays.

fix: implemented temporary workaround suggested by TileDB. (#2251)

---

server/compute/diffexp_cxg.py
server/data_cxg/cxg_adaptor.py
server/requirements.txt

- @bkmartinjr 
- @MDunitz 
- @ebezzi 
---
- remove: workaround code introduced by #58 and #60
- modify: upgraded [TileDB-Py to 0.10.1](https://github.com/TileDB-Inc/TileDB-Py/releases/tag/0.10.1) which includes the fix for the [`Array.multi_index` concurrency bug](https://github.com/TileDB-Inc/TileDB-Py/pull/672).
- verified by reproducing the crash locally on 0.10.0 and without the workaround code, upgrading to 0.10.1 and running the same diffexp against the same dataset multiple times crash free
- will run the same tests once deployed to staging

fix: upgraded tiledb and reverted workaround (#61)

---

Makefile

@ebezzi
@MDunitz 
---
- modify `Makefile`'s `lint-server` to exclude build-related files.

chore: Ignore build files from linting

---

server/eb/app.py

- @tihuan 
- @blrnw3 
---
- add localhost and canary env as allowed origins

feat: include localhost and canary env as allowed origins for staging backend

---

client/__tests__/e2e/screenshot_env.js
client/configuration/eslint/eslint.js
client/configuration/webpack/webpack.config.shared.js
client/index_template.html
server/eb/app.py

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1210
@seve 
@MDunitz 
---
This PR adds Plausible script to `client/index_template.html`, and we change Plausible's `data-domain` attribute based on `DEPLOYMENT_STAGE` env value
BONUS:
This PR also updates ESLint to ignore `no var require` rule in `.js` files, since it's false positive
There's a [complementary Infra PR](https://github.com/chanzuckerberg/single-cell-infra/pull/434) that I think is needed in order for FE build step to get `DEPLOYMENT_STAGE`
PTAL thank you!

chore: 1210 Add Plausible

---

server/tests/unit/eb/test_eb.py

It fails if 'make pydist' is not run, which installs the server code. This change allows it to run without the server code being installed.
TODO: move EB tests outside of the unit tests (story to come)

Fix flaky EB test

---

server/app/app.py
server/data_common/cache.py
server/tests/unit/common/config/test_dataset_config.py
server/tests/unit/common/config/test_server_config.py
server/tests/unit/common/test_api.py

- @atolopko-czi 
- @ebezzi 
---
- modify cache code. Update dataset cache to use path to dataset as the cache key (instead of the explorer_url). Invalidate items in the metadata cache when particular errors are raised.
Update tests to use symlinks to allow for dataset cache key change

fix: invalidate metadata cache when dataset fails to load

---

client/src/actions/index.ts
client/src/components/app.tsx
client/src/components/datasetSelector/datasetSelector.tsx
client/src/components/datasetSelector/truncatingBreadcrumb.tsx

@seve, @ebezzi 
---
* Updated home and collection breadcrumbs to open in new tab if there is user work in progress (that is, updates in the LSB or RSB).
* Linting of existing dataset selector-related actions.

Added WIP check for home and collection links. (#124)

---

client/src/actions/index.ts
client/src/globals.ts
client/src/util/stateManager/datasetMetadataHelpers.ts

@tihuan, @ebezzi 
---
- Filtered out large datasets (where cell count is greater than 2 million) on response from `/dataset-metadata`.

Filtered out large datasets. (#141)

---

client/src/actions/index.ts
client/src/globals.ts

@tihuan 
---
- Added `explainNewTab` query string param to Home and Collections links when user has work in progress, in order to pop corresponding toast in the Portal.
[Corresponding Data Portal PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/1555)

Added param to Portal links if WIP. (#135)

---

server/app/app.py
server/common/config/server_config.py
server/data_common/dataset_metadata.py
server/default_config.py
server/requirements-dev.txt
server/requirements.txt
server/tests/fixtures/czi_hosted_server_config_outline.py
server/tests/unit/common/test_api.py

The cached data can become stale when datasets are revised/tombstoned. The caching of dataset s3 url "lookup" result will not be needed as the s3 url will be directly provided in requests in api v0.3.
@Bento007 
@danieljhegeman 
---
Remove all mention of the dataset metadata cache manager.

rm dataset metadata cache manager [#168]

---

client/index.html
client/index_template.html
client/src/actions/annotation.ts
client/src/actions/index.ts
client/src/common/types/entities.ts
client/src/globals.ts

**Functional:** @tihuan 
**Readability:** @Bento007, @MillenniumFalconMechanic 
---
- add
- `s3URIFetch`
- `updateAPIWithS3()` swaps out preloaded API embedded in HTML with S3URI prefix
- remove
- modify
- Modify templates to use `v0.3`
- Changed naming of some endpoint request helper functions to better reflect fetch vs fetchAndLoad
- Various typing and type safety

feat: client uses v0.3 api

---

server/requirements.txt

any sc-eng
any sc-eng
---
tiledb version 0.10.4 update was erroneously committed for local dev purposes, and does not agree with the single-cell-infra requirements.txt, causing deploy failure.  Could update in single-cell-infra, but better to upgrade tiledb more deliberately; in particular, tiledb 0.11.x is available now.

revert tiledb ver to 0.10.1

---

server/app/api/util.py
server/tests/unit/common/apis/test_api_v3.py

**Functional:**  @atolopko-czi 
**Readability:** @seve 
---
Remove trailing slash from the s3_uri that is used in the `/s3_uri/<s3_uri>/api/v0.3` requests, to ensure that all requests are properly utilizing the CloudFront cache. This woull change this:
`/cellxgene/s3_uri/s3%253A%252F%252Fhosted-cellxgene-dev%252Fpbmc3k.cxg%252F/api/v0.3/genesets`
to this
`/cellxgene/s3_uri/s3%253A%252F%252Fhosted-cellxgene-dev%252Fpbmc3k.cxg/api/v0.3/genesets`
- remove the trailing slash from S3_URIs before returning in GET */s3_uri

fix: remove trailing slash from s3_uri

---

server/app/api/util.py
server/data_common/dataset_metadata.py
server/tests/unit/common/apis/test_api_v3.py

---
- add check when s3_uri is None
- add typing
- add additional testing

Fix: return response caching

---

server/app/api/__init__.py

@Bento007 
---
The cache control headers were no longer being applied to a coding error introduced during refactoring. This was causing the dataset index endpoint to be cached by CloudFront, which meant that changes to the tombstone status were not being handled by the backend.  It also means that all other endpoints that specified the `@cache_control` annotation were not having cache control headers applied.
Verified that https://rdev-164-caching-redesign-explorer.rdev.single-cell.czi.technology/e/d0e594f3-26b8-4598-810f-4054760e0d45.cxg/  responds with `cache-control: no-store` header. Cannot the full tombstoning flow in rdev, since CloudFront is not configured on rdev. Will need to do final test in dev env.

fix: tombstoned datatset index page redirect

---

server/Makefile
server/requirements-dev.txt
server/tests/e2e/test_api_cache.py
server/tests/unit/common/apis/test_api_v2.py

**Functional:** @atolopko-czi 
---
related to https://github.com/chanzuckerberg/single-cell-explorer/issues/200
- add
- remove
- modify

fix: verify caching headers for dataset-metadata

---

.github/workflows/push-rdev.yml
scripts/happy

---
Add explicit --stack-name option for GHA-based builds of docker images. Replaces the use of --extra-tag to pass in the stack name. This allows the script to work in non-GHA build usages.
Tested:
* single-cell-infra happy explorer + data portal rdev *local* create
* single-cell-infra happy explorer + data portal rdev *GHA* create
* single-cell-data-portal happy *local* create

fix rdev non-GHA builds

---

server/requirements-dev.txt

@seve @atolopko-czi 
---
- The newest version of Black requires click 8.0.0 which isn't compatible with our other requirements.

chore: pin black version to avoid breaking compatibility with click 8

---

server/dataset/dataset_metadata.py
server/tests/unit/common/apis/test_api_v2.py

@atolopko-czi @MDunitz 
---
- Adds the `publisher_metadata` field to the dataset metadata endpoint call.

feat: add publisher_metadata to the dataset metadata endpoint

---

hosted/requirements.txt
server/dataset/cxg_dataset.py
server/requirements.txt
server/tests/unit/dataset/test_cxg_dataset.py

Bump tiledb dependency to 0.13.1, and add _temporary_ work-around for dense array read bug.  Add test case to verify the work-around resolves the issue.
**Functional:** @metakuni @atolopko-czi 
---
- add tiledb==0.13.1 to requirements files.
- add test case (modified version of test case from Ben, borrowed from #234)

bump tiledb to 0.13.1, add work-around for dense read bug

---

server/dataset/cxg_dataset.py

---
- modify: replaced deprecated `tiledb.Array()` with `tiledb.open()`

chore: replaced deprecated method to open TileDB array (#56)

---

.happy/config.json
docker-compose.yml

Make sure we build/run x86 images everywhere.
See https://github.com/chanzuckerberg/czgenepi/pull/999/files 
---
- add
- remove
- modify

fix: Docker-compose specify platform to get around arm vs amd arch mismatches

---

server/requirements.txt

In reaction to [this Portal update](https://github.com/chanzuckerberg/single-cell-data-portal/pull/2214/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R26)

bump tiledb ver, to stay on par with portal (tiledb writer)

---

Makefile
dev_docs/developer_guidelines.md
launch_dev_server.sh
server/requirements-dev.txt

**Functional:** @ebezzi 
**Readability:** N/A
---
- Added flake8 as a dependency in the dev requirements. Without this, the linter commands were failing.
- Modified the top-level Makefile so that sections of commands were clearer.
- Moved information around in the developer guidelines to make the instructions more clear. Also removed outdated commands and deprecated information about annotations.

chore: Clean up development guidelines.

---

.happy/config.json
.happy/terraform/envs/staging/main.tf
.happy/terraform/envs/staging/modules/dns/main.tf
.happy/terraform/envs/staging/modules/dns/outputs.tf
.happy/terraform/envs/staging/modules/dns/variables.tf
.happy/terraform/envs/staging/modules/ecs-stack/main.tf
.happy/terraform/envs/staging/modules/ecs-stack/outputs.tf
.happy/terraform/envs/staging/modules/ecs-stack/variables.tf
.happy/terraform/envs/staging/modules/service/main.tf
.happy/terraform/envs/staging/modules/service/variables.tf
.happy/terraform/envs/staging/outputs.tf
.happy/terraform/envs/staging/providers.tf
.happy/terraform/envs/staging/variables.tf

chore: happy terraform staging

---

.happy/terraform/envs/prod/main.tf

@atolopko-czi 
---
- add
- remove
- modify

chore: set explorer instance count to 3

---

client/src/components/geneExpression/gene.tsx
client/src/components/geneExpression/geneInfo/geneInfo.tsx
client/src/globals.ts

@colinmegill @hthomas-czi 
---
- replace drag handle in genesets with gene info button
- add gene info icon at top right of pop-up
- make gene info icon not primary color (until clicked)
To save space on the right sidebar, replaced the unused drag handle in genesets with the gene info icon. Changed the icon to grayscale, since it's not a primary action. Added icon to the top left of gene info card for continuity. Considering changing the info icon to something less general (for example, a document), especially since the info icon is already used in "About cellxgene" in the menu. @hthomas-czi @colinmegill What are your thoughts on these changes?

chore: gene info icon and minor design changes

---

client/src/components/graph/overlays/centroidLabels.tsx

Calculating centroids took ~75% of every first color-by. For example, in the 4m cell dataset, coloring by a categorical for the first time took 2 seconds, 1.5 of which are the centroids. 
This PR makes it so centroids are only calculated if the overlay is displayed.
Part of this epic: #327

fix: added flag to avoid calculating centroid if overlay isn't displayed

---

client/src/components/graph/graph.tsx
client/src/components/scatterplot/scatterplot.tsx
client/src/globals.ts
client/src/util/stateManager/colorHelpers.ts

This PR removes `computePointColors` from the graph and scatterplot components. It was a redundant function that was required to translate an RGB array (an array of arrays of length 3) into a contiguous Float32Array of length #cells*3. Here, we cut out the middleman and directly calculate `colorTable.rgb` to be the Float32Array.

fix: update colorTable code so linear scan only happens once

---

.github/workflows/push-rdev.yml
.happy/requirements.txt

Switches the workflow to use the go client. 
This successful run uses the yaml copied into this PR: https://github.com/chanzuckerberg/single-cell-explorer/actions/runs/2719326953
@atolopko-czi

fix: make push rdev use happy go client

---

client/src/actions/index.ts
client/src/components/geneExpression/gene.tsx
client/src/components/geneExpression/geneInfo/geneInfo.tsx
client/src/components/geneExpression/geneInfo/style.ts
client/src/components/leftSidebar/index.tsx
client/src/reducers/controls.ts

@seve 
---
- add warning banner for gene info responses that are not from ensembl ID
- incorporate new endpoint variable (is_ensembl_id_result) into logic
If NCBI does not initially return a response to a gene ID search, the data portal endpoint will search via gene name instead. If this search has only 1 result, we will show this result. However, these are not exact matches to ENSEMBL IDs, so this PR adds a warning banner for these responses that says "NCBI did not return an exact result to this gene"

feat: gene info api callback

---

client/configuration/webpack/webpack.config.prod.js

@seve 
---
- modify public path on webpack for static font files
Font files are being accessed currently on prod / dev by an incorrect URL path (duplicate /static/ folders), so this hopefully fixes that

fix: change path for static font files

---

client/src/common/types/entities.ts
server/tests/fixtures/test_bad_config.yaml
server/tests/fixtures/test_config.yaml

[331](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/331)
[336](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/336)
---
- Add 'donor_Id' to Standard Categories
- Add 'suspension_type' to Standard Categories
- Add 'self_reported_ethnicity' and 'self_reported_ethnicity_ontology_term_id' to Standard Categories. 
- Note: in the interim, we will support both 'ethnicity' and 'self_reported_ethnicity' fields in Standard Categories. Once the data portal is migrated over to 3.0.0, we will remove support for ethnicity as a Standard Category (as it will be a deprecated column name in cellxgene schema 3.0.0 in favor of self_reported_ethnicity)
- Will …

feat: add cellxgene schema 3.0.0 fields to Standard Categories

---

client/src/reducers/cascade.ts

refactor(cascadeReducer): Quick feedback

---

client/src/reducers/categoricalSelection.ts
client/src/reducers/centroidLabels.ts
client/src/reducers/continuousSelection.ts
client/src/reducers/datasetMetadata.ts
client/src/reducers/layoutChoice.ts
client/src/reducers/quickGenes.ts

This is probably the closest we could get to typing actions without using [Redux Toolkit](https://redux.js.org/usage/usage-with-typescript#overview), which is their strongly recommended way to do Redux now. 
The overall pattern is that each slice's reducer's `action` argument is `AnyAction`, since any action goes through every reducer. But in the switch case, we cast the action to the slice's action type, since such action type **should** come with the agreed payload. Note that this is NOT guaranteed at runtime, because Explorer is NOT using action creators to allow TypeScript to map the action type and payload statically. But such refactor would take a lot more time, so this is a compromise for now until we see a strong need to start using Redux Toolkit

refactor(cascadeReducer): Quick feedback 2

---

server/dataset/cxg_dataset.py

The new CXGs are not valid because the updated version is not included in the list of allowed versions. This PR is a one-liner to fix that.

Add CXG version 0.3.0 to list of allowed versions.

---

client/src/util/dataframe/dataframe.ts

Fixes #453 
Cause of the bug:
A change to `mapColumns` in `dataframe.ts`, where dictionary-encoded arrays are auto-converted to an array of their values, resulted in a mismatch between the column schema (still comprised of integers) and the column array (now comprised of values). This change was initially introduced in the dictionary-encoded flatbuffer PR so that engineers would not need to handle dictionary-encoded arrays specifically in the `mapColumns` callback (in `dataframe.ts`).
The clipping functionality uses `mapColumns` (the only place that uses this function) and returns the dataframe column without manipulation for categorical data. The dataframe column is now an array of values, but the schema still sees categories as integers.
The easiest fix is to simply revert `mapColumns` …

fix: Fix behavior of annotation labels when continuous clipping is active.

---

docker-compose.yml

See here for explanation: https://github.com/chanzuckerberg/single-cell-data-portal/pull/3351

fix: remove platform spec from docker compose yaml to unblock deployments

---

server/dataset/cxg_dataset.py

Fixes #491 
`cxg_dataset.py` was not configured to check for version `0.3.0`. Version parsing using `packaging.version` was added to more elegantly parse and compare version strings.

fix: Fixed issue where config was not generating properly due to CXG version upgrade

---

client/src/reducers/controls.ts
client/src/reducers/undoableConfig.ts

Fixes #481 
Undoing/Redoing through any of the genecard functions exploded the client because `controls.ts` reducer was not properly configured. State was being written to (and initialized for some variables) in place, which broke the history stack.
@seve 
@seve

fix: Gene info cards no longer break undo/redo

---

client/src/components/framework/layout.tsx

Reverts chanzuckerberg/single-cell-explorer#502
This did not solve the problem on `dev`.

unfix: Revert "fix: Assume NavBar is present when calculating height of explorer initially."

---

client/src/components/continuousLegend/index.tsx

https://github.com/chanzuckerberg/single-cell-explorer/issues/512

fix: Continuous legend properly disappears after coloring by continuous metadata and subsequently coloring by anything else

---

pyproject.toml
server/dataset/dataset_metadata.py
server/tests/unit/common/apis/test_api_v3.py

This will help when debugging error between explorer and data portal. Most importantly it give us the request_id so we can correlate with the data portal logs.
- Update the pyproject.toml to include our current ruff configuration.

Log failed responses from data portal

---

launch_dev_server.sh
server/cli/launch.py
server/tests/unit/__init__.py

Fixes local development bug introduced in #500 
Debug mode wasn't set properly as the CLI was updated to use the default config, in which debug is set to false. I updated `launch_dev_server.sh` to use `-d` flag to set debug.
I also added localhost as an allowed origin when debug is true.

chore: fix local development

---

server/requirements-dev.txt

Renames a dependency that was deprecated. The new name is `coverage`.

chore: rename codecov to coverage

---

hosted/Dockerfile

Issue #564 
Update the Docker base image to Ubuntu 22. This implicitly brings the default Python version to 3.10.

chore: update Docker base image to ubuntu 22

---

client/__tests__/e2e/cellxgeneActions.ts
client/__tests__/e2e/e2e.test.ts
client/src/components/graph/graph.tsx
client/src/util/camera.ts

- increase zoom limit to 12x from 3x
- add smoke test for zoom
- prevent scrolling on graph component
- tested locally and smoke tested
Previously, scrolling behavior conflicts with zoom tool:
https://user-images.githubusercontent.com/16548075/231508562-a850bf9c-8861-442f-bdbc-122236288540.mov
Now, the rubberbanding scrolling behavior is no longer present on the graph component:
https://user-images.githubusercontent.com/16548075/231508671-2467c602-80b2-4d17-afd9-42eee2b294a2.mov

feat: increase zoom limits by a factor of 4

---

server/requirements.txt

This should fix an issue where the binary endpoints are broken.

fix: pin Wekzeug to 2.2.3

---

.happy/terraform/envs/staging/main.tf

Decrease memory usage to 14G. This will allow running the explorer on an r5.large machine.

chore: decrease memory usage in staging explorer

---

scripts/explorer-with-portal-rdev.patch
scripts/patch-explorer-to-find-portal-rdev-stack.sh

The `tmp-rdev` branch changes allow an Explorer RDev stack to find the associated Portal RDev stack when making API calls during manual testing.  
This PR captures the `tmp-rdev` branch diff as a patch file and commits it to the repo for posterity. This PR also adds a script to apply the patch reliably. 
Upon merging this, the `tmp-rdev` branch can be removed.

chore: add script to patch explorer to find portal rdev stack

---

client/src/components/geneExpression/quickGene.tsx

#679 
Added logic to exclude genes where `feature_is_filtered:True` from the Quick Gene Search

fix(explorer): filter out where feature_is_filtered is true

---

client/src/components/datasetSelector/truncatingBreadcrumbs.tsx

addresses this ticket: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-explorer/599
none of the existing breadcrumb states would result in both the collection + dataset breadcrumbs using "short text". this PR fixes that by adding that as a state. additionally, since there's only two breadcrumbs, we only need to have two `BreadcrumbState`s in `BreadcrumbsState`.
i ran this locally and verified we showed "Collection > Dataset" if the screen was sufficiently small enough.
https://github.com/chanzuckerberg/single-cell-explorer/assets/5653616/b5649091-f2a4-4d8e-9b70-d18de322442c
note for posterity: in order to run this locally, i had to [mock the dataset-metadata endpoint](https://github.com/chanzuckerberg/single-cell-explorer/blob/mai …

feat: update breadcrumbs to be truncated to include Collection

---

.github/workflows/deploy-happy-stack.yml

Workflow wasn't finding the package-lock during the setup node step

ci: correctly locate package-lock

---

client/__tests__/e2e/cellxgeneActions.ts

It seems like updating the config to `maxRetry: 200` consistently pass all the tests. I'll merge it to `main` to see if it works in GHA lol

chore: Update e2e test timeout to prevent flaky tests

---

client/src/actions/index.ts
client/src/components/categorical/category/index.tsx
client/src/components/categorical/index.tsx
client/src/reducers/controls.ts

Removed author and standard categories for cellguide cxgs and added singletons back. This is controlled by a new application state variable called "isCellGuideCxg" which is inferred at launchtime by parsing the URL.

feat: remove author and standard categories for cellguide cxgs and add singletons back

---

client/index.html
client/src/globals.ts

- Fixes an issue with the new REGEX not properly updating the API prefix when selecting a new dataset
- Fixes an issue with trailing slashes when trying to access a CXG on localhost:3000 (this broke local e2e tests).
The "REGEX_PATHNAME_FOR_DATASET_SELECTOR" is what the original regex was prior to the changes made for enabling access to CXGs in S3 subfolders
Tested in a pirated `dev` deployment since we do not have test infrastructure for testing dataset selection.

fix: fix regex API prefix substitution for dataset selection

---

client/src/actions/index.ts

> So the /spatial/meta endpoint is 404'ing, but it’s 404'ing when trying to access via cellxgene/e/super-cool-spatial.cxg/api/v0.3/spatial/meta not cellxgene/s3_uri/s3%253A%252F%252Fhosted-cellxgene-dev%252Fsuper-cool-spatial.cxg/api/v0.3/spatial/meta

fix(spatial): use global api prefix for /spatial/meta calls

---

server/dataset/dataset.py

This is a fix for get_spatial() to return `None` instead of `e` when `uns` array is missing
Tests:
- Pulled same unaltered dataset from s3 (spatial without `uns`)
- Ran locally with spatial embedding
- Tested altered (spatial with `uns`)
- Ran locally with spatial embedding

fix: missing uns array returns error instead of None

---

client/__tests__/e2e/e2e.test.ts

`open gene info card and hide/remove` seems to still be flaky because the click on minimize geneInfo card wasn't registered. So I've added tryUntil around the action and assertion pair for each test step!

test: fix e2e test

---

client/src/components/graph/setupLasso.ts

#843 
Lasso wasn't cancelling correctly because the function was always expecting the close path to be defined, even thought it almost never is.

fix: fix lasso canceling by removing definition checking

---

.github/workflows/deploy-happy-stack.yml
.github/workflows/push_tests.yml
client/__tests__/e2e/cellxgeneActions.ts
client/__tests__/e2e/e2e.test.ts
client/configuration/lint-staged/lint-staged.config.js
client/src/components/menubar/index.tsx
client/src/components/util/truncate.tsx

1. Add Chromatic screenshots where the graph matters
2. Stabilize test steps by using `tryUntil()` and short assertion timeout to fail fast and retry
3. Add `data-chromatic="ignore"` to more elements

test: Add chromatic screenshots for all tests

---

server/common/constants.py
server/common/rest.py
server/common/utils/uns.py
server/common/utils/utils.py
server/dataset/dataset.py
server/tests/__init__.py
server/tests/unit/common/apis/test_api_v3.py

Added 2 unit tests:
`test_uns_no_metadata_get` - for dataset without `uns` array or spatial
`test_uns_metadata_get` - for dataset with `uns` array and spatial
Slight refactor to extract metadata helper functions to a dedicated utils file

fix: unit tests and slight refactor

---

client/src/components/embedding/index.tsx
client/src/components/menubar/index.tsx
client/src/reducers/controls.ts

Old redux action handling image underlay display state was error-prone. This PR removes the reducer's implicit state toggling with explicit state sent via the action payload

fix: remove implicit state toggling for spatial underlay in favor of explicit state setting

---

client/src/components/hotkeys/index.tsx

Subsetting with the hotkey (SHIFT+W) when 0 cells are selected caused an error in the crossfilter. Subset is not possible with 0 cells through the menubar to avoid this edge case, so the same restriction is now applied to the hotkey subset.

chore: prevent subset when 0 cells are selected

---

client/src/components/graph/graph.tsx
client/src/components/graph/types.ts
client/src/components/menubar/diffexpButtons.tsx
client/src/components/menubar/index.tsx
client/src/util/camera.ts

close #910
1. Add Home Button ONLY to spatial mode, because it turned out to be pretty difficult to detect when the embedding layer is out of the viewport or not, whereas Openseadragon has built in feature we can leverage to check it
2. Only show the Home Button when the image is fully out of the viewport
3. Add back pan and zoom bound to NON-SPATIAL modes, so they don't need the home button
Implementation:
1. On Openseadragon `viewport-change` event, we run a function to check if the image layer is in viewport or not and set new state `isImageLayerInViewport` if it's different from the current state
2. `render` function will just check `isImageLayerInViewport` to see if it should render the home button
3. Home button on click will call `goHome()` function, which triggers Openseadragon to …

feat: Home button

---

client/src/components/graph/graph.tsx
client/src/components/graph/util.ts

1. Extract image download logics into its own method `handleImageDownload()`
2. Update `handleImageDownload()` to turn both openseadragon and graph canvases into png, and then draw on offscreen canvas, then convert to another PNG, then download
Demo:
https://github.com/chanzuckerberg/single-cell-explorer/assets/6309723/67acff82-4d9f-4db9-a29e-347db8bf345a
Download legend too:
https://github.com/chanzuckerberg/single-cell-explorer/assets/6309723/83b5d16d-d00f-461a-b583-61b712991bc6

fix: Export image update

---

client/src/actions/config.ts
client/src/common/selectors.ts
client/src/components/graph/graph.tsx
client/src/components/graph/types.ts
client/src/components/graph/util.ts
client/src/components/menubar/index.tsx
client/src/reducers/config.ts
client/src/selectors/config.ts

fix: #940
1. Move state `isDeepZoomSourceValid` into `config` reducer, so both Graph and Menubar components can use that state
2. Extract selector `shouldShowOpenseadragon` to `client/src/common/selectors.ts` to be used by the components above
3. Create `config` selector file
https://github.com/chanzuckerberg/single-cell-explorer/assets/6309723/7d12238b-e172-46f4-9d94-4decc71f3490

fix: 940 hide image toggle

---

client/src/actions/index.ts
client/src/components/embedding/index.tsx
client/src/reducers/layoutChoice.ts
client/src/selectors/annoMatrix.ts
client/src/selectors/layoutChoice.ts

Fix #936 
1. `doInitialDataLoad` action now choose the initial layout by checking if the dataset's preferred `default_embedding` is available or not and fall back to picking the best layout given the available layouts
2. This resolves two bugs:
1. On page load, we no longer get the layout flickering caused by the layoutChoice first setting a fallback layout, and then switching to the dataset preferred layout
2. Fixes #936
3. Extract a new selector `selectAvailableLayouts ` to reuse
https://github.com/chanzuckerberg/single-cell-explorer/assets/6309723/ac978673-82d4-4b72-be01-a41593d2b2da

fix: 936 embedding cell count

---

client/src/actions/embedding.ts

fix #858
Context:
1. Jason discovered a bug where when switching from an embedding with less cells to an embedding with more cells (e.g., `umap` -> `spatial`), some cells in `spatial` embedding will remain unselected
2. The reason is because the cross filter unnecessarily keeps previous embedding dimension in its `dimensions` property when the selection mode is `all`, which causes `BitArray.countAllOnes` to return the selection intersection of both `umap` and `spatial` dimensions, which is the lesser amount
Solution:
1. The fix proposed by @seve and @atarashansky (thanks so much for both of your help!) is to explicitly drop the current embedding dimension from the cross filter, IF `graphSelection.selection.mode === "all"`
Proof that subsetting in one embedding will keep the subset when …

fix: 858 jason bug 2

---

client/src/util/constants.ts

Talked to Nik and we think setting 80 as the new max is reasonable
zoom level 12: <-------- CURRENT MAX
zoom level 40:
zoom level 50:
zoom level 60:
zoom level 70:
zoom level 80: <-- NEW MAX
zoom level 90:
zoom level 100:

feat: Bump max zoom from 12 to 80

---

server/dataset/dataset.py

This fixes the HTTP error thrown when navigating to aggregated datasets spatial embedding in explorer

fix: empty object triggers spatial normalization

---

.github/workflows/conventional-commits.yml
.infra/rdev/values.yaml

Adds a CI job to enforce that PR titles use conventional commit messages in support for Argus + release-please. This ensures that release-please includes changes in the release PRs for Argus
Ref: 
- https://github.com/googleapis/release-please?tab=readme-ov-file#release-please
- https://www.conventionalcommits.org/en/v1.0.0/

chore: enforce conventional commits

---

client/__tests__/e2e/e2e.test.ts
client/__tests__/util/helpers.ts
client/src/components/PanelEmbedding/constants.ts
client/src/components/PanelEmbedding/index.tsx
client/src/components/graph/graph.tsx
client/src/components/graph/types.ts
client/src/components/graph/util.ts

closes #1001
1. This PR addresses the comment by @ainfeld and @niknak33 that when the side panel is open BUT minimized, we should not download its image ([slack](https://chanzuckerbergteam.slack.com/archives/C0743HLEWMC/p1718918988252109?thread_ts=1718907751.998779&cid=C0743HLEWMC))

fix: 1001 No download image for minimized panel

---

.infra/staging/values.yaml

Bump memory limit for staging stack to prevent 137 exit codes from Kubernetes

chore: bump staging memory

---

client/src/components/categorical/category/index.tsx

fixes #1022 
Source of bug:
https://github.com/chanzuckerberg/single-cell-explorer/pull/977#discussion_r1667138687

fix: 1022 Fix color by category bug

---

.github/workflows/conventional-commits.yml
release-please-config.json

Upgrade to use to get more conventional commit types: https://github.com/chanzuckerberg/github-actions/pull/279
Also update release-please to recognize the additional types

chore: Update conventional commit GHA

---

.infra/rdev/values.yaml
client/__tests__/e2e/e2e.test.ts
client/src/components/graph/graph.tsx
client/src/util/camera.ts
client/src/util/constants.ts
client/src/util/glHelpers.ts

Added condition in `camera` to limit zoom level for `hires` to 12.0 - otherwise default to SCALE_MAX value (80.0)

feat: limit zoom level for hires

---

.infra/rdev/values.yaml
client/__tests__/e2e/e2e.test.ts
client/src/components/diffexNotice/index.tsx
client/src/components/geneExpression/infoPanel/index.tsx
client/src/components/geneExpression/infoPanel/style.ts

Changed info panel tabs to SDS/MUI tabs - remove previous implementation

fix: info panel tabs

---

.infra/rdev/values.yaml
client/src/components/geneExpression/infoPanel/datasetInfo/datasetInfoFormat.tsx
client/src/components/geneExpression/infoPanel/geneInfo/style.ts
client/src/components/geneExpression/infoPanel/style.ts

<details open>
<br />
<table>
<tr>
<th>Name</th>
<td>kaloster-sidebar-fix-2</td>
</tr>
<tr>
<td>composed-bee</td>
</tr>
<tr>
<td><a href="https://composed-bee.dev-sc.dev.czi.team" target="_blank">https://composed-bee.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
As per Harley

fix: padding of info panel content

---

.github/workflows/workflow-argus-docker-build.yaml
.infra/rdev/values.yaml
client/__tests__/e2e/cellxgeneActions.ts
client/__tests__/e2e/e2e.test.ts
client/src/components/NavBar/index.tsx
client/src/components/continuousLegend/index.tsx
client/src/components/embedding/components/Opacities/components/Opacity/index.tsx
client/src/components/embedding/components/Opacities/components/Opacity/style.ts
client/src/components/embedding/components/Opacities/index.tsx
client/src/components/embedding/components/Opacities/style.ts
client/src/components/embedding/components/Opacities/types.ts
client/src/components/embedding/index.tsx
client/src/components/embedding/style.ts
client/src/components/graph/graph.tsx
client/src/components/graph/types.ts
client/src/components/menubar/index.tsx
client/src/reducers/controls.ts

<details open>
<br />
<table>
<tr>
<th>Name</th>
<td>thuang-6867-image-dot-opacity</td>
</tr>
<tr>
<td>unbiased-glowworm</td>
</tr>
<tr>
<td><a href="https://unbiased-glowworm.dev-sc.dev.czi.team" target="_blank">https://unbiased-glowworm.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
1. Add `Opacities` component to control both image and dots opacity
2. Move Image Toggle button to the left side as part of the `Embedding` component
***KNOWN ISSUES***
1. The opacity control is persistent across different embedding types and shared between main and side panels
2. For example, if you set dot opacity to 50% and switch embedding to a non-spatial one, the dots will still be at 50% opacity
- <img …

feat: 6867 6868 image and dot opacity

---

.infra/rdev/values.yaml
client/__tests__/e2e/e2e.test.ts
client/__tests__/util/typedCrossfilter/crossfilter.test.ts
client/src/actions/selection.ts
client/src/components/graph/graph.tsx
client/src/components/util/truncate.tsx
client/src/reducers/graphSelection.ts
client/src/util/typedCrossfilter/types.ts

1. Add `graphId` to lasso selection reducer state
2. Use the new `graphId` to determine whether to display the lasso element in the panel or not
3. We only display the lasso element in the panel that initiated the lasso
https://github.com/user-attachments/assets/cf2aa442-f862-4151-bccf-10c11bd8de5d

fix: Remove the wrong lasso in the other panel

---

.infra/rdev/values.yaml
client/src/components/graph/graph.tsx

<details open>
<br />
<table>
<tr>
<th>Name</th>
<td>rainandbare-add-mix-blend-mode</td>
</tr>
<tr>
<td>evolving-hippo</td>
</tr>
<tr>
<td><a href="https://evolving-hippo.dev-sc.dev.czi.team" target="_blank">https://evolving-hippo.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
Fixes Issue #1040 
1. Add `mix-blend-mode` to canvas element in order to view under lying image better
Before: 
After:

fix: Add mix blend mode to canvas

---

.infra/rdev/values.yaml
client/__tests__/e2e/e2e.test.ts

I see that this test is flaky in GHA, so hopefully this fix helps!
My suspicion is that in GHA the downloads happen slower, so the assertion needs to run in a tryUntil 
```
Retry #2 ───────────────────────────────────────────────────────────────────────────────────────
16825 Error: expect(received).toBe(expected) // Object.is equality
16826
16827 Expected: 2
16828 Received: 1
16829
16830 1525 | await page.getByTestId("download-graph-button").click();
16831 1526 |
16832 > 1527 | expect(downloads.length).toBe(2);
16833 | ^
16834 1528 |
16835 1529 | const afterMinimizeDownloads: Download[] = [];
16836 1530 |
16837
16838 at /home/runner/work/single-cell-explorer/single-cell-explorer/client/__tests__/e2e/e2e.test.ts:1527:38
16839Notice: 1 failed
16840 [chromium] › e2e/e2e.test.ts:1514:15 › …
```

test: Make test more robust

---

.infra/rdev/values.yaml
client/src/common/constants.ts
client/src/components/brushableHistogram/histogram.tsx
client/src/components/brushableHistogram/utils.ts
client/src/components/geneExpression/infoPanel/infoPanelDataset/datasetInfoFormat.tsx
client/src/components/geneExpression/infoPanel/infoPanelGene/index.tsx
client/src/components/util/truncate.tsx

RDEV: https://absolute-sheepdog.dev-sc.dev.czi.team/d/super-cool-spatial.cxg?spatial=true
<details open>
<br />
<table>
<tr>
<th>Name</th>
<td>thuang-1053-add-truncation</td>
</tr>
<tr>
<td>absolute-sheepdog</td>
</tr>
<tr>
<td><a href="https://absolute-sheepdog.dev-sc.dev.czi.team" target="_blank">https://absolute-sheepdog.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
https://github.com/user-attachments/assets/7c9542ae-c57a-4837-8c0f-f183cd226e5b

fix: 1053 Truncate histogram and dataset info panel

---

.infra/rdev/values.yaml
client/__tests__/e2e/e2e.test.ts

GHA staging e2e test failed due to expecting 332 cells but got 331 cells. This PR takes both 332 and 331 into account!

test: Fix e2e test cellCount diff by 1

---

.infra/rdev/values.yaml
client/src/util/glHelpers.ts

context: https://czi-sci.slack.com/archives/C0247APK621/p1723740853441439?thread_ts=1723740810.796559&cid=C0247APK621
RDEV: https://well-bison.dev-sc.dev.czi.team/d/super-cool-spatial.cxg/
<details open>
<br />
<table>
<tr>
<th>Name</th>
<td>thuang-fix-spatial-highlight-dot-size</td>
</tr>
<tr>
<td>well-bison</td>
</tr>
<tr>
<td><a href="https://well-bison.dev-sc.dev.czi.team" target="_blank">https://well-bison.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
1. Update logic to check `isHighlight` first like the original method in `glPointSize`
https://github.com/user-attachments/assets/77c97227-cab3-46e7-8fc8-8646eed511f1

fix: Spatial mode dot size on highlight

---

client/src/components/framework/layout.tsx
client/src/components/framework/layoutSkeleton.tsx

The center Control Skeleton hasn't been working for a while, because the Layout component never called the render function!
This PR fixes it by adding a `...restChildren` in Layout and dump them along with the `graphComponent` in the center panel
https://github.com/user-attachments/assets/e6cc999f-307b-4c76-834f-f0edf6a27b56

fix: skeleton loader

---

.infra/rdev/values.yaml
client/index.html
client/index_template.html
client/src/components/theme.ts
server/ecs/app.py

<details open>
<br />
<table>
<tr>
<th>Name</th>
<td>thuang-fix-og-title-font-family</td>
</tr>
<tr>
<td>whole-finch</td>
</tr>
<tr>
<td><a href="https://whole-finch.dev-sc.dev.czi.team" target="_blank">https://whole-finch.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
Just realized that I had to add the meta tags in `index_template.html` as well in order to show up in the BE server served FE 🤦 One more reason to use Next.js to manage the FE build end to end!
Also updated the fontFamily declaration in the theme file to match the type shape, otherwise we get `undefined` for the SDS Chip style
Confirmed that the og:image works in FB Messenger this time!
Font Roboto Condensed is successfully loaded now! …

fix: og:title/image and fontFamily

---

.github/workflows/push_tests.yml
.github/workflows/scale-test.yml
.infra/rdev/values.yaml
dev_docs/developer_scripts.md
server/common/fbs/matrix.py
server/common/rest.py
server/dataset/dataset.py
server/requirements.txt
server/tests/unit/common/apis/test_api_v3.py
server/tests/unit/common/utils/test_type_conversion_utils.py

High priority:
- flask-cors 3.0.0 → 5.0.0 (security [patch](https://github.com/chanzuckerberg/single-cell-explorer/security/dependabot/99))
- pillow 9.5.0 → 10.2.0 (security [patch](https://github.com/chanzuckerberg/single-cell-explorer/security/dependabot/78)) (removed, leftover from MVP)
- werkzeug 2.2.3 → 3.0.3 (security [patch](https://github.com/chanzuckerberg/single-cell-explorer/security/dependabot/89))
- flask 2.2.3 → 2.2.5 (security [patch](https://github.com/chanzuckerberg/single-cell-explorer/security/dependabot/56))
Moderate:
- requests 2.28.2 → 2.32.0 ([moderate](https://github.com/chanzuckerberg/single-cell-explorer/security/dependabot/90))
- pydantic 1.10.6 → 1.10.13 ([moderate](https://github.com/chanzuckerberg/single-cell-explorer/security/dependabot/86))
Lower priority: …

chore: Upgrade BE deps (SCE-18)

---

.infra/rdev/Chart.yaml
.infra/staging/Chart.yaml

Updating the chart dependency since it's pretty old at this point. This will update it for staging and rdev, if staging looks good after this is merged I'll make another PR for prod

chore: bump chart versions

---

.github/workflows/e2e-tests.yml
.infra/rdev/values.yaml
client/package-lock.json
client/package.json

Replace `npm` codecov package with their official Github Action plugin as recommended on:
https://github.com/codecov/codecov-action/tree/v4.2.0/

chore: Upgrade codecov

---

.infra/rdev/values.yaml
client/index.html
client/index_template.html
client/src/components/NavBar/style.ts

https://happy-duck.dev-sc.dev.czi.team/d/super-cool-spatial.cxg/
<details open>
<br />
<table>
<tr>
<th>Name</th>
<td>thuang-fix-navbar-font-to-inter</td>
</tr>
<tr>
<td>happy-duck</td>
</tr>
<tr>
<td><a href="https://happy-duck.dev-sc.dev.czi.team" target="_blank">https://happy-duck.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
UPDATE (9/23): Restyled BetaChip to match Data Portal too!

fix: SCE-20 Navbar use font Inter

---

.infra/rdev/values.yaml
client/src/reducers/controls.ts

chore: default dot opacity 50% (SCE-27)

---

.infra/rdev/values.yaml
client/src/components/AnnoDialog/AnnoDialog.tsx
client/src/components/AnnoDialog/style.ts
client/src/components/AnnoDialog/types.ts
client/src/components/RightSideBar/components/GeneExpression/components/GeneSet/components/EditGenesetNameDialogue/EditGenesetNameDialogue.tsx
client/src/components/RightSideBar/components/GeneExpression/components/GeneSet/components/GeneSetMenus/components/AddGeneToGenesetDialogue/AddGeneToGenesetDialogue.tsx

Refactor of `AnnoDialog.tsx` from Class to Functional component

refactor: AnnoDialog (SCE-34)

---

.github/workflows/e2e-tests.yml
.infra/rdev/values.yaml

actions/cache@v1 is being deprecated in Feb 2025. Thanks again for the headsup, @hspitzley-czi ! 🙏

chore: Upgrade GHA actions

---

.github/workflows/argus-stack-prod-upsert.yaml
.github/workflows/argus-stack-rdev-create.yaml
.github/workflows/argus-stack-rdev-delete.yaml
.github/workflows/argus-stack-staging-upsert.yaml
.github/workflows/conventional-commits.yml
.infra/rdev/values.yaml

https://czi.atlassian.net/browse/CCIE-3911
This PR updates 'runs-on' in GitHub Actions workflow files to use direct values instead of label arrays.

fix: Update runs-on labels in GitHub Actions workflows

---

.infra/rdev/values.yaml
client/src/components/Graph/Graph.tsx
client/src/reducers/singleContinuousValue.ts
client/src/util/constants.ts
client/src/util/singleValues.ts
server/dataset/cxg_dataset.py

Related: https://github.com/chanzuckerberg/single-cell-explorer/issues/1146
This adds support for CytAssist Visium assays - slide size for scale bar calculation is now based on `assay_ontology_term_id`

chore: update for CytAssist

---

.github/workflows/docker-build-staging-prod.yaml
.github/workflows/workflow-argus-docker-build.yaml
.infra/rdev/values.yaml
hosted/Dockerfile

<details open>
<br />
<table>
<tr>
<th>Name</th>
<td>jakeyheath-patch-1</td>
</tr>
<tr>
<td>patient-terrapin</td>
</tr>
<tr>
<td><a href="https://patient-terrapin.dev-sc.dev.czi.team" target="_blank">https://patient-terrapin.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
https://czi.atlassian.net/browse/CCIE-4050
This upgrades to using v4.2.0 of the argus builder which has detection of whether a PR has the stack label built-in, ie rdev values.yaml will only be updated now when the stack label is on a PR
Additionally, and more importantly, this new version uses the newer self-hosted runners

chore: upgrade docker builder

---

.infra/prod/Chart.yaml
.infra/rdev/Chart.yaml
.infra/staging/Chart.yaml

https://czi.atlassian.net/browse/CCIE-4211
We have switched to using NLBs instead of ALBs, however in order to make use of these new network configurations, the application needs to run on the latest version of the helm chart.

chore: bump helm charts to make use of NLB

---

server/app/api/v3.py
server/app/app.py
server/common/constants.py
server/common/rest.py

<details open>
<br />
<table>
<tr>
</tr>
<tr>
<td>star-barnacle</td>
</tr>
<tr>
<td><a href="https://star-barnacle.dev-sc.dev.czi.team" target="_blank">https://star-barnacle.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---

feat: fix w routing to exclude static assets from glob

---

.infra/rdev/values.yaml
client/__tests__/e2e/cell-guide.test.ts
client/__tests__/e2e/e2e.test.ts
client/src/components/RightSideBar/components/GeneExpression/GeneExpression.tsx
client/src/components/RightSideBar/components/GeneExpression/components/Gene/Gene.tsx
server/default_config.py
server/tests/unit/common/config/__init__.py
server/tests/unit/common/config/test_dataset_config.py

<details open>
<br />
<table>
<tr>
</tr>
<tr>
<td>mature-elf</td>
</tr>
<tr>
<td><a href="https://mature-elf.dev-sc.dev.czi.team" target="_blank">https://mature-elf.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
Related to: https://github.com/chanzuckerberg/single-cell-explorer/issues/1231 and https://github.com/chanzuckerberg/single-cell-explorer/issues/1233
RDEV - https://mature-elf.dev-sc.dev.czi.team/d/super-cool-spatial.cxg/
Users reported issues where:
- Gene list under GeneSets were not appearing when using Differential Expression feature
- Genes are missing from gene search
Changes:
- Updated Gene Expression logic to handle DE genesets while …

fix: GeneSets bug

---

.infra/rdev/values.yaml
client/__tests__/e2e/e2e.test.ts
client/src/actions/geneset.ts
client/src/actions/index.ts
client/src/annoMatrix/normalize.ts
client/src/common/components/BrushableHistogram/BrushableHistogram.tsx
client/src/common/constants.ts
client/src/components/RightSideBar/components/GeneExpression/GeneExpression.tsx
client/src/components/RightSideBar/components/GeneExpression/components/Gene/Gene.tsx
client/src/components/RightSideBar/components/GeneExpression/components/Gene/types.ts
client/src/components/RightSideBar/components/GeneExpression/components/GeneSet/GeneSet.tsx
client/src/components/RightSideBar/components/GeneExpression/components/QuickGene/QuickGene.tsx
client/src/components/scatterplot/scatterplot.tsx
client/src/util/stateManager/colorHelpers.ts
server/default_config.py
server/tests/unit/common/config/__init__.py
server/tests/unit/common/config/test_dataset_config.py

<details open>
<br />
<table>
<tr>
</tr>
<tr>
<td>natural-hermit</td>
</tr>
<tr>
<td><a href="https://natural-hermit.dev-sc.dev.czi.team" target="_blank">https://natural-hermit.dev-sc.dev.czi.team</a></td>
</tr>
</table>
</details>
---
Related to: https://github.com/chanzuckerberg/single-cell-explorer/issues/1231 and https://github.com/chanzuckerberg/single-cell-explorer/issues/1233
- Updated key functionality to use `feature_name` var column to support post 6.0 schema migrations CxGs
- Reverted the previous implementation
- Added fallback to support test dataset and scenarios where `feature_name` column is not present

fix: Update Explorer to use feature_name

---

client/src/common/hooks/useChromatinViewerSelectedGene.tsx
server/dataset/cxg_dataset.py

Updated the ChromatinViewerProvider to dynamically detect genome version and default gene (MYC for human, Vip for mouse) from the dataset's organism ontology term ID.

fix: Grab organism_ontology_term_id from config
